# Generated by Django 2.1.2 on 2018-10-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181027_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterClinicDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_a', to='app.ClinicLocation')),
                ('location_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_b', to='app.ClinicLocation')),
            ],
        ),
    ]
