# Generated by Django 2.1.2 on 2018-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_interclinicdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLINIC_MANAGER', 'Clinic Manager'), ('WAREHOUSE_PERSONNEL', 'Warehouse Personnel'), ('DISPATCHER', 'Dispatcher')], default='CLINIC_MANAGER', max_length=200),
        ),
    ]
