# Generated by Django 2.1.2 on 2018-11-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTokenRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('CLINIC_MANAGER', 'Clinic Manager'), ('WAREHOUSE_PERSONNEL', 'Warehouse Personnel'), ('DISPATCHER', 'Dispatcher')], default='CLINIC_MANAGER', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordering_clinic',
        ),
        migrations.AddField(
            model_name='order',
            name='i',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClinicLocation'),
        ),
    ]
