# Generated by Django 2.1.3 on 2018-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('3', 'HIGH'), ('2', 'MEDIUM'), ('1', 'LOW')], default='2', max_length=200),
        ),
    ]
