# Generated by Django 2.1.2 on 2018-11-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181115_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='i',
            new_name='ordering_clinic',
        ),
    ]
