# Generated by Django 2.1.2 on 2018-11-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181116_0922'),
        ('app', '0016_auto_20181116_1425'),
    ]

    operations = [
    ]
