# Generated by Django 2.1.3 on 2018-11-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20181116_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QUEUED_FOR_PROCESSING', 'Queued for Processing'), ('PROCESSING_BY_WAREHOUSE', 'Processing by Warehouse'), ('QUEUED_FOR_DISPATCH', 'Queued for Dispatch'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='QUEUED_FOR_PROCESSING', max_length=200),
        ),
    ]
