# Generated by Django 2.1.2 on 2018-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181119_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='csv_file_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
