# Generated by Django 2.1.2 on 2018-11-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_shipment_csv_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password',
            field=models.BooleanField(default=False),
        ),
    ]
