# Generated by Django 2.1.2 on 2018-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile_forgot_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forgot_password',
        ),
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
