# Generated by Django 2.1.2 on 2018-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181129_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_label_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
