# Generated by Django 2.1.2 on 2018-10-28 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_interclinicdistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('QUEUED_FOR_PROCESSING', 'Queued for Processing'), ('PROCESSING_BY_WAREHOUSE', 'Processing by Warehouse'), ('QUEUED_FOR_DISPATCH', 'Queued for Dispatch'), ('DISPATCHED', 'Dispatched')], default='QUEUED_FOR_PROCESSING', max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='clinic_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClinicLocation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLINIC_MANAGER', 'Clinic Manager'), ('WAREHOUSE_PERSONNEL', 'Warehouse Personnel'), ('DISPATCHER', 'Dispatcher')], default='CLINIC_MANAGER', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='app.OrderedItem', to='app.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordering_clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClinicLocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplying_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.HospitalLocation'),
        ),
    ]
